tutorial.o: tutorial.cpp ../testfuncs/benchmarks.hpp \
 ../testfuncs/benchmark.hpp ../interval/interval_air.hpp \
 ../common/utilmacro.hpp ../interval/enums.h ../derivatives/valder.hpp \
 ../derivatives/grad.hpp ../interval/enums.h \
 ../derivatives/intervalder.hpp ../expression/expr.hpp \
 ../expression/node.hpp ../expression/algorithm.hpp \
 ../expression/expr.hpp ../expression/utils.h ../expression/algder.hpp \
 ../testfuncs/testfuncs.hpp
tutorialbnb.o: tutorialbnb.cpp ../testfuncs/benchmarks.hpp \
 ../testfuncs/benchmark.hpp ../interval/interval_air.hpp \
 ../common/utilmacro.hpp ../interval/enums.h ../derivatives/valder.hpp \
 ../derivatives/grad.hpp ../interval/enums.h \
 ../derivatives/intervalder.hpp ../expression/expr.hpp \
 ../expression/node.hpp ../expression/algorithm.hpp \
 ../expression/expr.hpp ../expression/utils.h ../expression/algder.hpp \
 ../testfuncs/testfuncs.hpp
tutorialgrad.o: tutorialgrad.cpp ../testfuncs/benchmarks.hpp \
 ../testfuncs/benchmark.hpp ../interval/interval_air.hpp \
 ../common/utilmacro.hpp ../interval/enums.h ../derivatives/valder.hpp \
 ../derivatives/grad.hpp ../interval/enums.h \
 ../derivatives/intervalder.hpp ../expression/expr.hpp \
 ../expression/node.hpp ../expression/algorithm.hpp \
 ../expression/expr.hpp ../expression/utils.h ../expression/algder.hpp \
 ../testfuncs/testfuncs.hpp
